Friendship v2
themonster2015/fb-replica pull request #1
Opened 2021-06-15 17:44 UTC by themonster2015

Hi,

Please check and approve my submission. Thank you!

2021-06-15 20:02 UTC, SajjadAhmad14 commented on app/views/users/_user.html.erb
>    <% end %>
Put this logic in a view helper in app/helpers and render it here.

2021-06-15 20:07 UTC, SajjadAhmad14 requested changes
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, you have been doing a tremendous job so far :ok_hand:
## To Highlight 🎉
- [ ] Commit messages are descriptive.
- [ ] Project UI has very good features.
## To Improve 🙏
- [ ] There should be a main/master branch that is used for production releases.
- [ ] PR description should include the information about features of the project.
- [ ] README should include `rails db:create` step before `rails db:migrate`.
- [ ] Please add Github actions so that linter checks can show on PR.
- [ ] `AddDefaultValueToFriendshipConfirmedMigrations` migration is failed to run. Kindly fix it.
- [ ] There is no option on the navigation to send friendship requests to other users.
- [ ] User is unable to see all users with the Friend Request button next to users who are not their friends already.
- [ ] This error occurs when a user has friendship requests and he clicks on the notifications button.
![notification](https://user-images.githubusercontent.com/35504149/122115407-e4176f00-ce3d-11eb-86e4-35cb9cf26ab6.png)
- [ ] User is unable to accept incoming friendship requests. Please see this error.
![friendship_error](https://user-images.githubusercontent.com/35504149/122115498-ff827a00-ce3d-11eb-9370-bfff77d5abb6.png)
- [ ] User is unable to reject incoming friendship requests. Please see this error.
![friendship_reject_error](https://user-images.githubusercontent.com/35504149/122115543-0a3d0f00-ce3e-11eb-88f1-469fdcee9f37.png)
- [ ] User should be able to see all posts by him and by his friends.
- [ ] Please see inline comments for reference.
# Optional
- [ ] Views should be separate from logic. You can put logic in view helpers under app/helpers and render them in views.
### Happy Coding ☺️
## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

2021-06-16 10:43 UTC, themonster2015 commented
first of all, thanks for the comments and feedback
can you explain to me this step: Please add Github actions so that linter checks can show on PR?

also the accept friend request, reject friend request, view posts from friends and self on the dashboard functions work well on my computer

i don't know why they display errors on your side

![Screen Shot 2021-06-15 at 22 33 01](https://user-images.githubusercontent.com/10905837/122204944-fd510780-ce9f-11eb-8892-fb953b42351e.png)
![Screen Shot 2021-06-15 at 22 26 51](https://user-images.githubusercontent.com/10905837/122204951-ff1acb00-ce9f-11eb-90af-0d5f8c07048c.png)
![Screen Shot 2021-06-15 at 22 26 39](https://user-images.githubusercontent.com/10905837/122204953-004bf800-cea0-11eb-8b8b-4cef69284523.png)
![Screen Shot 2021-06-15 at 22 26 20](https://user-images.githubusercontent.com/10905837/122204955-004bf800-cea0-11eb-8259-8c1bb31f3421.png)

2021-06-16 11:21 UTC, carlos-ssh requested changes
**_Hello Team_** 👋🏽👋🏽👋🏽
**_Your project is really nice. I like it!!!_** 👏🏽

**Kindly work on this requested changes:**
- Remove this message ```--- !ruby/object:ActionController::Parameters
parameters: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  controller: posts
  action: index
permitted: false ```
- When I create a post within a new account and then logout and access to a new one i can see the posts from other users.
- If i accept a new friend request the app crashes: 
![Screen Shot 2021-06-16 at 06 18 19](https://user-images.githubusercontent.com/22258274/122209905-a977fb80-ce6a-11eb-8c24-cbb809227481.png)
- If I reject a friend request the app crashes: 
![Screen Shot 2021-06-16 at 06 19 07](https://user-images.githubusercontent.com/22258274/122210006-c3b1d980-ce6a-11eb-81b0-9a4271350426.png)

**Kindly work on this requested changes and after create a new code review.**
**_Happy Coding!_** 👨🏽‍💻
@carlos-ssh

2021-06-16 13:30 UTC, themonster2015 commented
Hi,

Thanks very much for your feedback. I've fixed it.

2021-06-16 13:46 UTC, mke2111 approved these changes
# 😄 🥇  STATUS: APPROVED  🥇 👏🏽 

## Hey Happy Coder, 👋🏽 
Congratulations, 🥂 . You got minimum requirements for approval. 👍🏽 

### **_Well Done_** 💯 

    1. The app runs as expected and doesn't crash any more


### You may now merge to the develop branch and remember to submit a project completion form.
### I wish you the very best in your upcoming projects.

**Cheers 🍹 and Happy coding 💻** 

<hr>

### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

2021-06-16 14:00 UTC, merged